export let design_pattern_list = [
    {'Repository': 'action-list', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'bottomsheet', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'collapsible', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'complex-bottomsheet', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'data-list', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'dynamic-stepper','git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'form-validation', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'icon-navigation', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'internationalization', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'login', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'multiselect-list', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'responsive-table', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'search-bar', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'side-navigation', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'sortable-list', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'status-list', 'git': 'https://github.com/pxblue/action-list',
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/action-list/tree/angular', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://circleci.com/gh/pxblue/action-list/tree/react', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Updated': [{'a' : 'https://github.com/pxblue/action-list/commits/angular', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/angular.svg?label=angular&style=flat'},
            {'a' : 'https://github.com/pxblue/action-list/commits/react', 'img' : 'https://img.shields.io/github/last-commit/pxblue/action-list/react.svg?label=react&style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
];
