export let npm_package_list = [
    {'Repository': 'colors', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'component-library', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'highcharts', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'icons', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'icons-mui', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'mapbox', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'symbols-mui', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
    {'Repository': 'themes', 'git': 'https://github.com/pxblue/colors/tree/master',
    'Npm': [{'a' : 'https://www.npmjs.com/package/@pxblue/colors', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors.svg?label=@pxblue/colors&style=flat'}, {'a' : 'https://www.npmjs.com/package/@pxblue/colors-branding', 'img' : 'https://img.shields.io/npm/v/@pxblue/colors-branding.svg?label=@pxblue/colors-branding&style=flat'}],
    'Status': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Updated': [{'a' : 'https://circleci.com/gh/pxblue/colors/tree/master', 'img' : 'https://img.shields.io/circleci/project/github/pxblue/colors/master.svg?style=flat'}],
    'Issues' : [{'a' : 'https://github.com/pxblue/colors/issues?q=is%3Aissue+is%3Aopen+label%3Abug', 'img' : 'https://img.shields.io/github/issues/pxblue/colors/bug.svg?style=flat&label=bugs'}]},
];
